spring:
  application:
    name: backend-service

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres  # Replace with actual DB name
    username: postgres                              # Replace with actual DB username
    password: 123456                              # Replace with actual DB password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate # Ensures Hibernate only validates that the schema matches the DB structure, avoiding accidental drops.
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
